name: Build and Publish to GHCR
on: 
  push:
    branches: master
    tags: "*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Determine tags
      id: prep
      run: |
        BASE=ghcr.io/${{ github.repository }}
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          TAGNAME=$(echo ${GITHUB_REF#refs/heads/} | sed -e "s/^refs\/tags\///")
          TAGS="${BASE}:sdk-$TAGNAME"
        else  
          TAGS="${BASE}:latest"
        fi
        echo ::set-output name=tags::${TAGS}

    - name: Checkout code
      uses: actions/checkout@master

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.prep.outputs.tags }}
